/* A (yet very incomplete) list of country codes according to ISO 3166. */
codesISO3166 = {
  'AD': {de: 'Andorra', en: 'Andorra'},
  'AF': {de: 'Afghanistan', en: 'Afghanistan'},
  'AG': {de: 'Antigua und Barbuda', en: 'Antigua and Barbuda'},
  'AI': {de: 'Anguilla', en: 'Anguilla'},
  'AL': {de: 'Albanien', en: 'Albania'},
  'AO': {de: 'Angola', en: 'Angola'},
  'AQ': {de: 'Antarktika', en: 'Antarctica'},
  'AS': {de: 'Amerikanisch-Samoa', en: 'American Samoa'},
  'AU': {de: 'Australien', en: 'Australia'},
  'AW': {de: 'Aruba', en: 'Aruba'},
  'AX': {de: 'Ålandinseln', en: 'Åland'},
  'AZ': {de: 'Aserbaidschan', en: 'Azerbaijan'},
  'BE': {de: 'Belgien', en: 'Belgium'},
  'BG': {de: 'Bulgarien', en: 'Bulgaria'},
  'BH': {de: 'Bahrain', en: 'Bahrain'},
  'BO': {de: 'Bolivien', en: 'Bolivia'},
  'BS': {de: 'Bahamas', en: 'Bahamas'},
  'BR': {de: 'Brasilien', en: 'Brazil'},
  'BY': {de: 'Weißrussland', en: 'Belarus'},
  'CA': {de: 'Kanada', en: 'Canada'},
  'CI': {de: 'Elfenbeinküste', en: 'Ivory Coast'},
  'CL': {de: 'Chile', en: 'Chile'},
  'CN': {de: 'China', en: 'China'},
  'CR': {de: 'Costa Rica', en: 'Costa Rica'},
  'CU': {de: 'Kuba', en: 'Cuba'},
  'CW': {de: 'Curaçao', en: 'Curaçao'},
  'DE': {de: 'Deutschland', en: 'Germany'},
  'DK': {de: 'Dänemark', en: 'Denmark'},
  'DZ': {de: 'Algerien', en: 'Algeria'},
  'EC': {de: 'Ecuador', en: 'Ecuador'},
  'EE': {de: 'Estland', en: 'Estonia'},
  'EG': {de: 'Ägypten', en: 'Egypt'},
  'ES': {de: 'Spanien', en: 'Spain'},
  'FI': {de: 'Finnland', en: 'Finland'},
  'FR': {de: 'Frankreich', en: 'France'},
  'GB': {de: 'Vereinigtes Königreich', en: 'Great Britain'},
  'GR': {de: 'Griechenland', en: 'Greece'},
  'HK': {de: 'Hongkong', en: 'Hongkong'},
  'HT': {de: 'Haiti', en: 'Haiti'},
  'ID': {de: 'Indonesien', en: 'Indonesia'},
  'HR': {de: 'Kroatien', en: 'Croatia'},
  'IE': {de: 'Irland', en: 'Ireland'},
  'IL': {de: 'Israel', en: 'Israel'},
  'IN': {de: 'Indien', en: 'India'},
  'IS': {de: 'Island', en: 'Iceland'},
  'IT': {de: 'Italien', en: 'Italy'},
  'JP': {de: 'Japan', en: 'Japan'},
  'KZ': {de: 'Kasachstan', en: 'Kazakhstan'},
  'LV': {de: 'Lettland', en: 'Latvia'},
  'MO': {de: 'Macau', en: 'Macao'},
  'MT': {de: 'Malta', en: 'Malta'},
  'MX': {de: 'Mexiko', en: 'Mexico'},
  'NL': {de: 'Niederlande', en: 'Netherlands'},
  'NO': {de: 'Norwegen', en: 'Norway'},
  'NZ': {de: 'Neuseeland', en: 'New Zealand'},
  'PL': {de: 'Polen', en: 'Poland'},
  'PT': {de: 'Portugal', en: 'Portugal'},
  'RU': {de: 'Russische Föderation', en: 'Russian Federation'},
  'SA': {de: 'Saudi-Arabien', en: 'Saudi Arabia'},
  'SI': {de: 'Slowenien', en: 'Slovenia'},
  'SL': {de: 'Slowakei', en: 'Slovakia'},
  'SN': {de: 'Senegal', en: 'Senegal'},
  'SV': {de: 'El Salvador', en: 'El Salvador'},
  'TR': {de: 'Türkei', en: 'Turkey'},
  'US': {de: 'Vereinigte Staaten von Amerika', en: 'United States of America'},
  'VI': {de: 'Amerikanische Jungferninseln', en: 'Virgin Islands (U.S.)'}
};